articles/urls.py
# coding=utf-8


from django.urls import path

from . import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('load/', views.load, name='load_articles'),
]

newsfeels/urls.py
# coding=utf-8


from django.contrib import admin
from django.urls import include, path

from articles import urls as articles_urls

urlpatterns = [
    path('articles/', include(articles_urls)),
    path('admin/', admin.site.urls),
]

articles/models.py
# coding=utf-8


import hashlib
from uuid import UUID

from django.db import models

from newsfeels.settings.enums import ArticleSource, Sentiment


class Article(models.Model):
    """
    Model that represents an article that has been analyzed already.
    """
    source = models.CharField(max_length=10, choices=ArticleSource.choices())
    external_id = models.CharField(max_length=32, unique=True, editable=False)

    title = models.CharField(max_length=200)
    author = models.CharField(max_length=100)
    published = models.DateTimeField()
    url = models.URLField('URL')
    content = models.TextField()
    sentiment_label = models.CharField(max_length=10, choices=Sentiment.choices())
    sentiment_score = models.FloatField()

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ('source', 'external_id')
        ordering = ('-published',)

    def __str__(self):
        return '({}) {}'.format(self.get_source_display(), self.title)

    def __repr__(self):
        return '<Article "{}">'.format(self)

    def save(self, *args, **kwargs):
        if not self.external_id:
            uuid_components = (self.source, self.title, self.author, self.published, self.url)
            self.external_id = self._generate_hash(*uuid_components)
        super().save(*args, **kwargs)

    def get_sentiment_percentage(self):
        """
        Returns the sentiment score as a percentage value (form 0 to 100).
        e.g. -0.65 --> 65
        """
        return abs(self.sentiment_score)*100

    def get_sentiment_description(self):
        """
        Returns the sentiment as a nicely formatted string.
        e.g. "Positive (1.00)"
        """
        return '{} ({:.2f})'.format(self.get_sentiment_label_display(), self.sentiment_score)

    @classmethod
    def create_articles(cls, source, available_articles):
        """
        Takes a list of 3-tuple with data from articles and creates new DB records, if articles are new.
        """
        current_count = cls.objects.all().count()

        for article_content, key_information, sentiment in available_articles:
            title = key_information['title']
            author = key_information['author']
            published = key_information['published']
            url = key_information['url']
            possible_external_id = cls._generate_hash(source, title, author, published, url)

            if not cls.objects.filter(external_id=possible_external_id).exists() and article_content:
                data = {
                    'source': source,
                    'external_id': possible_external_id,
                    'title': title,
                    'author': author,
                    'published': published,
                    'url': url,
                    'content': article_content,
                    'sentiment_label': sentiment['label'],
                    'sentiment_score': sentiment['score'],
                }
                cls.objects.create(**data)

        new_count = cls.objects.all().count()
        some_article_created = current_count != new_count
        return some_article_created

    @staticmethod
    def _generate_hash(source, title, author, published, url):
        source_data = ''.join(str(x) for x in [source, title, author, published, url]).encode('utf-8')
        return hashlib.md5(source_data).hexdigest()

articles/views.py
# coding=utf-8


from django.http import HttpResponse
from django.views import generic

from sources.utils import load_articles

from .models import Article


class IndexView(generic.ListView):
    """
    Main view of the `articles` app.
    """
    template_name = 'articles/index.html'

    def get_queryset(self):
        return Article.objects.all()


def load(request):
    """
    Small view that triggers the process for pulling articles and analyzing them.
    """
    if load_articles():
        return HttpResponse('OK')
    return HttpResponse(status=204)

articles/templates/articles/index.html
{% extends 'base.html' %}
{% load articles_utils %}


{% block main_container %}
    {% if article_list %}
        <table class="table table-responsive">
            <caption class="text-small"><a id="loader" href="{% url 'load_articles' %}">Load more articles</a></caption>
            <thead>
                <tr>
                    <th scope="col"></th>
                    <th scope="col">Source</th>
                    <th scope="col">Article</th>
                    <th scope="col">Published</th>
                    <th scope="col">Sentiment</th>
                </tr>
            </thead>
            <tbody>
            {% for article in article_list %}
                {% with label=article.sentiment_label bs_color=article.sentiment_label|get_sentiment_bs_color %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ article.get_source_display }}</td>
                        <td>
                            <p>
                                <a href="{{ article.url }}" target="_blank"><strong>{{ article.title }}</strong></a>
                                <br/>
                                <span class="text-small"></span>{{ article.author }}</span>
                            </p>
                        </td>
                        <td class="text-small">{{ article.published|date:"M d" }}<br/>{{ article.published|date:"P" }}</td>
                        <td class="text-large text-center" title="{{ article.get_sentiment_description }}">
                            {% if label == 'positive' %}🙂{% elif label == 'negative' %}😠{% else %}😐{% endif %}
                            <div class="progress">
                                <div 
                                    class="progress-bar bg-{{ bs_color }}" role="progressbar"
                                    style="width: {{ article.get_sentiment_percentage }}%"
                                    aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"
                                ></div>
                            </div>
                        </td>
                    </tr>
                {% endwith %}
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        No data yet. Hold on for a bit and let us take care.
    {% endif %}
{% endblock main_container %}

newsfeels/templates/base.html
<!doctype html>
{% load static %}


<html lang="en-US">

<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>NewsFeels</title>
  <meta name="description" content="NewsFeels analyzes the sentiment of new articles and stories from media outlets - powered by IBM's Watson NLU">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">
  {% block scripts_head %}
  <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
  {% endblock scripts_head %}
</head>

<body>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-10 offset-md-1">
        <div id="big_container">
          <h1>
            {% block body_title %}📰 NewsFeels{% endblock body_title %}
          </h1>
          <p><small class="text-muted">
            Analyzing sentiments of new articles and stories from media outlets.<br/>
            Powered by News API and IBM's Watson NLU
          </small></p>
          <div id="main_container">{% block main_container %}{% endblock main_container %}</div>
          <p id="about">&copy;2018 Julian Perez - julianperez.me</p>
        </div>
      </div>
    </div>
  </div>
  {% block scripts_body %}
    <script type="text/javascript">
      $(document).ready(function () {
        var loader = $("#loader");
        if (loader !== null) {
          loader.click(function(e) {
            e.preventDefault();
            loader.text('Loading...');
            $.ajax({
              url: loader.attr('href'),
              statusCode: {
                200: function() { location.reload() },
                204: function() { loader.text('Nothing new, try again.') }
              }
            });
          });
        }
      });
    </script>
  {% endblock scripts_body %}
</body>

</html>